// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RefugioAnimales.Models.BBDD;

#nullable disable

namespace RefugioAnimales.Migrations
{
    [DbContext(typeof(RefugioContext))]
    [Migration("20251129133417_Usuario-Admin")]
    partial class UsuarioAdmin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RefugioAnimales.Models.Adoptante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaAlta")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Adoptantes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "JuanPerez@email.com",
                            FechaAlta = new DateOnly(2024, 12, 22),
                            Nombre = "Juan Pérez",
                            Telefono = "612345678"
                        },
                        new
                        {
                            Id = 2,
                            Email = "MariaPerez@email.com",
                            FechaAlta = new DateOnly(2024, 5, 11),
                            Nombre = "María Pérez",
                            Telefono = "612345679"
                        },
                        new
                        {
                            Id = 3,
                            Email = "JuanMariaPerez@email.com",
                            FechaAlta = new DateOnly(2023, 7, 3),
                            Nombre = "Juan María Pérez",
                            Telefono = "712345678"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AdoptanteId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAdopcion")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("FotoContenido")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("FotoMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdoptanteId");

                    b.HasIndex("EstadoId");

                    b.ToTable("Animales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Le gusta volar, no puede parar.",
                            Edad = 2,
                            Especie = "Colibrí",
                            EstadoId = 1,
                            FotoContenido = new byte[0],
                            Nombre = "Picudo"
                        },
                        new
                        {
                            Id = 2,
                            AdoptanteId = 1,
                            Descripcion = "Siempre esta pinchando cuando puede.",
                            Edad = 4,
                            Especie = "Erizo",
                            EstadoId = 2,
                            FechaAdopcion = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FotoContenido = new byte[0],
                            Nombre = "Pinchitos"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Canta la opera como si fuera su último día.",
                            Edad = 6,
                            Especie = "Loro",
                            EstadoId = 1,
                            FotoContenido = new byte[0],
                            Nombre = "Nemo"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.EstadoAnimal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EstadoAnimal");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estado = "Disponible"
                        },
                        new
                        {
                            Id = 2,
                            Estado = "Adoptado"
                        },
                        new
                        {
                            Id = 3,
                            Estado = "En cuarentena"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreUsuario = "admin",
                            PasswordHash = "",
                            Rol = "Admin"
                        });
                });

            modelBuilder.Entity("RefugioAnimales.Models.Animal", b =>
                {
                    b.HasOne("RefugioAnimales.Models.Adoptante", "Adoptante")
                        .WithMany("Animales")
                        .HasForeignKey("AdoptanteId");

                    b.HasOne("RefugioAnimales.Models.EstadoAnimal", "Estado")
                        .WithMany("Animales")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Adoptante");

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("RefugioAnimales.Models.Adoptante", b =>
                {
                    b.Navigation("Animales");
                });

            modelBuilder.Entity("RefugioAnimales.Models.EstadoAnimal", b =>
                {
                    b.Navigation("Animales");
                });
#pragma warning restore 612, 618
        }
    }
}
